In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
# Change the vector to 5 rows 1 col
a.shape = (5,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a[0][0]

1

In [10]:
a[0][1]

2

In [11]:
b = np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [12]:
b.shape = (2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

### Generating random matrix

In [13]:
a = np.random.randint(1,5,size=(3,3))
a

array([[4, 4, 2],
       [2, 2, 1],
       [4, 3, 2]])

In [14]:
b = np.random.randint(1,5,size=(3,3))
b

array([[4, 1, 4],
       [1, 2, 2],
       [4, 3, 2]])

In [15]:
c = np.random.randint(2,7,size=(3,3))
c

array([[2, 5, 3],
       [3, 3, 2],
       [2, 3, 6]])

### Transpose of a Matrix

In [16]:
a = np.array([[6,2],[3,1]])
a

array([[6, 2],
       [3, 1]])

In [17]:
a.T

array([[6, 3],
       [2, 1]])

In [20]:
b = np.array([[4,9,2],[5,7,1],[7,7,0]])
b

array([[4, 9, 2],
       [5, 7, 1],
       [7, 7, 0]])

In [21]:
b.T

array([[4, 5, 7],
       [9, 7, 7],
       [2, 1, 0]])

In [22]:
c = np.array([[9,7,8],[4,3,0],[4,9,8],[2,9,0]])
c

array([[9, 7, 8],
       [4, 3, 0],
       [4, 9, 8],
       [2, 9, 0]])

In [23]:
c.T

array([[9, 4, 4, 2],
       [7, 3, 9, 9],
       [8, 0, 8, 0]])

### Generating symmetric random matrix

In [24]:
b = np.random.randint(1,5,size=(3,3))
b

array([[2, 4, 4],
       [4, 4, 1],
       [3, 3, 4]])

In [25]:
b.T

array([[2, 4, 3],
       [4, 4, 3],
       [4, 1, 4]])

In [26]:
b_symm = b + b.T
b_symm

array([[4, 8, 7],
       [8, 8, 4],
       [7, 4, 8]])

In [27]:
b_symm.T

array([[4, 8, 7],
       [8, 8, 4],
       [7, 4, 8]])

### Matrix Addition in Numpy

In [28]:
a = np.random.randint(1,5,size=(2,2))
a

array([[1, 4],
       [1, 4]])

In [29]:
b = np.random.randint(1,5,size=(2,2))
b

array([[4, 1],
       [2, 4]])

In [31]:
c = a + b
c

array([[5, 5],
       [3, 8]])

### Matrix Multiplication

In [32]:
3 * a

array([[ 3, 12],
       [ 3, 12]])

In [35]:
a = np.array([[1,4,7],[2,5,8],[3,6,9]])
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
b = np.array([[1,4],[2,5],[3,6]])
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
np.dot(a,b)

array([[30, 66],
       [36, 81],
       [42, 96]])

In [41]:
a = np.array([[3,9],[1,9]])
b = np.array([[8,0]])
a * b

array([[24,  0],
       [ 8,  0]])

In [45]:
a = np.array([[9,7],[4,7]])
b = np.array([[3,5],[3,3]])
a * b

array([[27, 35],
       [12, 21]])

In [46]:
a = np.array([[2,6],[8,2],[4,2]])
b = np.array([[5,8,7],[7,6,1]])
a * b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

#### Properties

Multiplication

A(BC) = (AB)C

In [47]:
a = np.array([7,0])
b = np.array([[6,1],[7,7]])
c = np.array([[5],[5]])

In [50]:
np.dot(np.dot(a,b),c)

array([245])

In [51]:
np.dot(a,np.dot(b,c))

array([245])

In [53]:
a = np.array([[2,3],[4,1]])
b = np.array([[1,2],[3,1]])
c = np.array([[2,1],[5,3]])

In [54]:
np.dot(np.dot(a,b),c)

array([[57, 32],
       [59, 34]])

In [55]:
np.dot(a,np.dot(b,c))

array([[57, 32],
       [59, 34]])

#### Properties

Multiplication and transposition

(AB)' = B'A'

In [56]:
np.dot(a,b).T

array([[11,  7],
       [ 7,  9]])

In [57]:
np.dot(b.T,a.T)

array([[11,  7],
       [ 7,  9]])

#### Matrix: X'X

In [58]:
b = np.ones((5,1))
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [59]:
a = np.random.random((5,1))*10
a

array([[2.32537618],
       [0.47215262],
       [2.47236522],
       [8.38343553],
       [7.05960749]])

In [62]:
x = np.column_stack((b,a))
x

array([[1.        , 2.32537618],
       [1.        , 0.47215262],
       [1.        , 2.47236522],
       [1.        , 8.38343553],
       [1.        , 7.05960749]])

In [63]:
np.dot(x.T,x)

array([[  5.        ,  20.71293703],
       [ 20.71293703, 131.8629414 ]])

#### Matrix: e'e 

In [65]:
e = np.random.random((5,1))
e

array([[0.17034521],
       [0.06671281],
       [0.65488593],
       [0.59286598],
       [0.44107434]])

In [66]:
np.dot(e.T,e)

array([[1.00838032]])

### Diagonal Matrix

In [69]:
a = np.random.randint(1,5,size=(3,3))
a

array([[2, 1, 1],
       [4, 2, 4],
       [3, 2, 4]])

In [70]:
np.diagonal(a) # same as np.diag(a)

array([2, 2, 4])

In [72]:
np.diag([4,7,2])

array([[4, 0, 0],
       [0, 7, 0],
       [0, 0, 2]])

### Identity Matrix

In [73]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
b = np.ones((3,3), dtype=np.int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [77]:
np.identity(3,dtype=np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Null Matrix

In [78]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### The determinant of a Matrix

In [79]:
b = np.random.randint(1,5,size=(2,2))

In [81]:
np.round(np.linalg.det(b))

-2.0

In [83]:
a = np.random.randint(1,10,size=(3,3))
a

array([[1, 6, 6],
       [5, 2, 1],
       [9, 4, 3]])

In [84]:
np.round(np.round(np.linalg.det(a)))

-22.0

In [95]:
a = np.random.randint(1,5,size=(3,3))
a

array([[2, 4, 1],
       [3, 2, 3],
       [1, 2, 3]])

In [96]:
b = np.copy(a)
b

array([[2, 4, 1],
       [3, 2, 3],
       [1, 2, 3]])

In [100]:
b[0][0] = 3*a[0][0]
b[1][0] = 3*a[0][1]
b[2][0] = 3*a[0][2]
b

array([[ 6,  4,  1],
       [12,  2,  3],
       [ 3,  2,  3]])

In [101]:
np.round(np.round(np.linalg.det(a)))

-20.0

In [102]:
np.round(np.round(np.linalg.det(b)))

-90.0

In [103]:
a[0,:] = 2*a[1,:]
a

array([[6, 4, 6],
       [3, 2, 3],
       [1, 2, 3]])

In [104]:
adiag = np.diag(np.diag(a))
adiag

array([[6, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])