In [1]:
import pandas as pd
import numpy as np

In [2]:
d = pd.read_csv('E:/UConn/Course/Summer 2019/OPIM 5512/PPT/loans.csv')

In [3]:
d.head()

Loan_ID         loan_status  Principal  terms effective_date  \
0  xqd20160201             PAIDOFF       1000     15      9/12/2016   
1  xqd20160454  COLLECTION_PAIDOFF       1000     30      9/12/2016   
2  xqd20160278             PAIDOFF       1000     30      9/14/2016   
3  xqd20160051             PAIDOFF        800     15      9/11/2016   
4  xqd20160207             PAIDOFF       1000     30      9/12/2016   

     due_date     paid_off_time  past_due_days  age             education  \
0   9/26/2016    9/20/2016 8:26            NaN   30               college   
1  10/11/2016  10/14/2016 11:04            3.0   26  High School or Below   
2  10/13/2016   10/13/2016 9:00            NaN   31               college   
3   9/25/2016   9/25/2016 13:00            NaN   27               college   
4  11/10/2016  11/10/2016 13:00            NaN   26               college   

   Gender  
0    male  
1    male  
2    male  
3  female  
4    male

In [51]:
d.shape

(450, 14)

In [4]:
d.loc[(d.Gender=='male'), 'gcode'] = 0
d.loc[(d.Gender=='female'), 'gcode'] = 1

In [5]:
d.loan_status.unique()

array(['PAIDOFF', 'COLLECTION_PAIDOFF', 'COLLECTION'], dtype=object)

In [6]:
d.loc[(d.loan_status=='PAIDOFF'),'outcome']=0
d.loc[(d.loan_status=='COLLECTION'),'outcome']=1
d.loc[(d.loan_status=='COLLECTION_PAIDOFF'),'outcome']=2

In [7]:
d.education.unique()

array(['college', 'High School or Below', 'Bechalor', 'Master or Above'],
      dtype=object)

In [8]:
d.loc[(d.education=='college'),'ecode']=0
d.loc[(d.education=='High School or Below'),'ecode']=1
d.loc[(d.education=='Bechalor'),'ecode']=2
d.loc[(d.education=='Master or Above'),'ecode']=3

In [9]:
d.head()

Loan_ID         loan_status  Principal  terms effective_date  \
0  xqd20160201             PAIDOFF       1000     15      9/12/2016   
1  xqd20160454  COLLECTION_PAIDOFF       1000     30      9/12/2016   
2  xqd20160278             PAIDOFF       1000     30      9/14/2016   
3  xqd20160051             PAIDOFF        800     15      9/11/2016   
4  xqd20160207             PAIDOFF       1000     30      9/12/2016   

     due_date     paid_off_time  past_due_days  age             education  \
0   9/26/2016    9/20/2016 8:26            NaN   30               college   
1  10/11/2016  10/14/2016 11:04            3.0   26  High School or Below   
2  10/13/2016   10/13/2016 9:00            NaN   31               college   
3   9/25/2016   9/25/2016 13:00            NaN   27               college   
4  11/10/2016  11/10/2016 13:00            NaN   26               college   

   Gender  gcode  outcome  ecode  
0    male    0.0      0.0    0.0  
1    male    0.0      2.0    1.0  
2    male    0.0      0.0    0.0  
3  female    1.0      0.0    0.0  
4    male    0.0      0.0    0.0

In [33]:
y = d.outcome
X = d[['age', 'ecode', 'gcode']]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

D:\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [38]:
from sklearn.linear_model import Perceptron

In [77]:
ppn = Perceptron(max_iter=2000, eta0=0.001, random_state=0, tol=0.001)
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.001,
      fit_intercept=True, max_iter=2000, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=0.001,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [78]:
y_pred = ppn.predict(X_test_std)
print('Misclassified samples: %d' % (y_test != y_pred).sum())

Misclassified samples: 65


In [79]:
from sklearn.metrics import accuracy_score

In [80]:
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.52


In [81]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[65  3  7]
 [30  1  3]
 [20  2  4]]
              precision    recall  f1-score   support

         0.0       0.57      0.87      0.68        75
         1.0       0.17      0.03      0.05        34
         2.0       0.29      0.15      0.20        26

   micro avg       0.52      0.52      0.52       135
   macro avg       0.34      0.35      0.31       135
weighted avg       0.41      0.52      0.43       135



In [98]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.3, random_state=0)

In [99]:
sc2 = StandardScaler()
sc2.fit(X_train)
X_train_std2 = sc.transform(X_train2)
X_test_std2 = sc.transform(X_test2)

D:\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [100]:
ppn2 = Perceptron(max_iter=79, eta0=0.141, random_state=0, tol=0.0011)
ppn2.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.141,
      fit_intercept=True, max_iter=79, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=0.0011,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [101]:
y_pred2 = ppn2.predict(X_test_std2)
print('Misclassified samples: %d' % (y_test2 != y_pred2).sum())

Misclassified samples: 83


In [102]:
print('Accuracy: %.2f' % accuracy_score(y_test2, y_pred2))

Accuracy: 0.39
